### PR TITLE
Fix accessing template deprecation

### PR DESCRIPTION
**Pull request by mattmcmanus**
Should remove deprecation warning reported in #12

### CODE REVIEW

**Comment by mattmcmanus** [comment]
I should note: I just made this edit inside of github editor. I haven't yet checked it out to verify if it's worked.

**Comment by wcurtis** [comment]
Good to know - thanks for the heads up.

Any idea which version of Ember `hasBlock` was introduced? I'll need to look into best practices for updating ember addons that drop old ember version support (eg. ember versions pre `hasBlock`).

**Comment by mattmcmanus** [comment]
Looks like it's a 1.13 introduction: http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_component-block-info

I suppose that complicates things. The deprecations guide doesn't offer much help either about a transition plan. 

*(....googling....)*

Looks like it's easy to polyfil if you need to support old versions:

https://github.com/emberjs/ember.js/issues/11430#issuecomment-124988006

```js
if(Ember.VERSION.startsWith("1.12")) {
    Ember.Component.reopen({
        hasBlock: Ember.computed.alias('template')
    });
}
```

**Comment by wcurtis** [comment]
Nice find! That polyfil looks promising. Feel free to update the PR - I may not get to this for a little while.

**Comment by sbounmy** [comment]
+1 for this quick-win PR :)

**Comment by mattmcmanus** [comment]
Finally had a minute to sit down with this. I'm afraid I'm new enough to ember that I have no idea where I should put the polyfill. An instance-initializer?

**Comment by wcurtis** [comment]
Yeah sounds about right :+1:

**Comment by mattmcmanus** [comment]
Still not sure how to get this to work. Some notes:

1. Upgraded the project to ember-cli 1.13.8. This made it easy to setup ember try to make sure old versions still work
2. I've got the test in place and a way to setup the polyfill, but it doesn't want to work just yet. 

I'll come back to this at some point.

**Pull request closed without merging**
